### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by waldt** [cogsys-tuebingen/cslibs_math#1]
I could not build the library, I keep getting the errors:

[...]
CMake Error at /home/jaan/workspace/src/cslibs_math/cslibs_math_2d/CMakeLists.txt:30 (cslibs_math_add_unit_test_gtest):
  Unknown CMake command "cslibs_math_add_unit_test_gtest".
[...]
CMake Error at /home/jaan/workspace/src/cslibs_math/cslibs_math_3d/CMakeLists.txt:32 (cslibs_math_add_unit_test_gtest):
  Unknown CMake command "cslibs_math_add_unit_test_gtest".

**Comment by c-schulz** [comment]
Hi @waldt,

I'm sorry, but I can't reproduce your problem, neither with `cmake` nor with `catkin_make`. `cslibs_math_add_unit_test_gtest` is defined in [cslibs_math/cmake/cslibs_math_add_unit_test_gtest.cmake](https://github.com/cogsys-tuebingen/cslibs_math/blob/master/cslibs_math/cmake/cslibs_math_add_unit_test_gtest.cmake). How do you build your workspace?

Cheers

**Comment by waldt** [comment]
I am building with catkin_tools. The same error can be reproduced by using catkin_make_isolated .

**Comment by c-schulz** [comment]
Hi @waldt,

my bad, we confused makro names. Could you try again, please?

Cheers

**Comment by waldt** [comment]
Builds now, thanks!
