### ISSUE TITLE
does not compile with clang

### ISSUE THREAD

**Issue by waldt** [cogsys-tuebingen/cslibs_math#2]
...
In file included from /home/workspace/src/cslibs_math/cslibs_math/test/hausdorff.cpp:1:
In file included from /home/workspace/src/cslibs_math/cslibs_math/include/cslibs_math/linear/hausdorff.hpp:5:
/home/workspace/src/cslibs_math/cslibs_math/include/cslibs_math/statistics/distribution.hpp:28:27: error: constexpr variable 'sqrt_2_M_PI' must be initialized by a constant expression
  static constexpr double sqrt_2_M_PI = std::sqrt(2 * M_PI);
...

The reason is that std::sqrt is not defined as constexpr according to C++ standard (gcc is too permissive here)

**Comment by c-schulz** [comment]
Hi @waldt,

I implemented a `constexpr` version of `sqrt` in `cslibs_math::common::sqrt`. Could you try again, please?

Cheers
