### ISSUE TITLE
cslibs_math build error

### ISSUE THREAD

**Issue by lisilin013** [cogsys-tuebingen/cslibs_math#3]
Dear authors,

Thanks for your opensource code, here when I build this package, the terminal gives me some error like this:

Error showed in terminal is
>cslibs_math/statistics/stable_distribution.hpp:241:80: error: operands to ?: have different types ‘const Eigen::CwiseUnaryOp<Eigen::internal::scalar_abs_op<double>, const Eigen::Matrix<double, 3, 1> >’ and ‘cslibs_math::statistics::StableDistribution<double, 3ul, 3ul>::eigen_values_t {aka Eigen::Matrix<double, 3, 1>}’
         return (dirty_eigenvalues_ && valid()) ?  update_return_eigen() : (abs ? eigen_values_.cwiseAbs() : eigen_values_);

The reference code is 
https://github.com/cogsys-tuebingen/cslibs_math/blob/32600b2ea4d0683af46a8c5fd8bd36bf5652955e/cslibs_math/include/cslibs_math/statistics/distribution.hpp#L240

I notice that the c++ operator **? a : b** , a and b must be the same type, so I think this code confused me.

Looking forward to your reply!
Thanks again!

**Comment by lisilin013** [comment]
I just check the code again and I find how to solve this error.
replace the code
```
 updateEigenvalues(); return abs ? eigen_values_.cwiseAbs() : eigen_values_; 
```
with
```
 updateEigenvalues(); return abs ? eigen_values_t(eigen_values_.cwiseAbs()): eigen_values_; 
```

The second statement can convert the type of **eigen_values_.cwiseAbs()** to eigen_values_t type.

**Comment by c-schulz** [comment]
Hey @lisilin013 
I merged your pull request. Thanks a lot!
